// dubai page
describe("Test dubai destination page", () => {
        it("navigates to dubai page", () => {
            cy.visit("https://brianwhelandublin.github.io/milestone-project-2/destination.html?c0")
        })
        it("tests Dubai details", () => {
            cy.get(".des-page-title").should("contain", "Dubai")
            cy.get(".des-background-img").should("have.attr", "style").should("contain", "dubai-bg.jpg")
            cy.get(".flag").should("be.visible")
            cy.get(".details-item").should("be.visible")
            cy.get("#map").should("be.visible")
            cy.get(".package").then(item => {
                expect(item[0]).to.contain.text("€499/ person sharing")
                expect(item[1]).to.contain.text("€549/ person sharing")
                expect(item[2]).to.contain.text("€699/ person sharing")
            })
        })
        it("Tests Dubai navigation changes", () => {
            cy.get(".navigation-list").should("be.hidden")
            cy.get(".hamburger").click()
            cy.get(".navigation-list").should("be.visible")
            cy.get(".navigation-link").then(item => {
                expect(item[0]).to.contain.text("Home");
                expect(item[0]).to.have.attr("href", "index.html#home")
                expect(item[1]).to.contain.text("Dubai Details")
                expect(item[1]).to.have.attr("href", "#details")
                expect(item[2]).to.contain.text("Dubai Map")
                expect(item[2]).to.have.attr("href", "#map-section")
                expect(item[3]).to.contain.text("Dubai Packages")
                expect(item[3]).to.have.attr("href", "#destination-packages")
                expect(item[4]).to.contain.text("All Destinations")
                expect(item[4]).to.have.attr("href", "index.html#destinations")
                expect(item[5]).to.contain.text("Package Specials")
                expect(item[5]).to.have.attr("href", "index.html#special-packages")
                expect(item[6]).to.contain.text("Booking Enquiry")
                expect(item[6]).to.have.attr("href", "booking.html?c0")
                expect(item[7]).to.contain.text("Reviews")
                expect(item[7]).to.have.attr("href", "index.html#reviews")
                expect(item[8]).to.contain.text("Contact")
                expect(item[8]).to.have.attr("href", "index.html#contact")
            })
            cy.wait(2000)
        })
    })
    // Kyoto page
describe("Test Kyoto destination page", () => {
        it("navigates to Kyoto page", () => {
            cy.visit("https://brianwhelandublin.github.io/milestone-project-2/destination.html?c1")
        })
        it("tests Kyoto details", () => {
            cy.get(".des-page-title").should("contain", "Kyoto")
            cy.get(".des-background-img").should("have.attr", "style").should("contain", "kyoto-bg.jpg")
            cy.get(".flag").should("be.visible")
            cy.get(".details-item").should("be.visible")
            cy.get("#map").should("be.visible")
            cy.get(".package").then(item => {
                expect(item[0]).to.contain.text("€599/ person sharing")
                expect(item[1]).to.contain.text("€649/ person sharing")
                expect(item[2]).to.contain.text("€799/ person sharing")
            })
        })
        it("Tests Kyoto navigation changes", () => {
            cy.get(".navigation-list").should("be.hidden")
            cy.get(".hamburger").click()
            cy.get(".navigation-list").should("be.visible")
            cy.get(".navigation-link").then(item => {
                expect(item[0]).to.contain.text("Home");
                expect(item[0]).to.have.attr("href", "index.html#home")
                expect(item[1]).to.contain.text("Kyoto Details")
                expect(item[1]).to.have.attr("href", "#details")
                expect(item[2]).to.contain.text("Kyoto Map")
                expect(item[2]).to.have.attr("href", "#map-section")
                expect(item[3]).to.contain.text("Kyoto Packages")
                expect(item[3]).to.have.attr("href", "#destination-packages")
                expect(item[4]).to.contain.text("All Destinations")
                expect(item[4]).to.have.attr("href", "index.html#destinations")
                expect(item[5]).to.contain.text("Package Specials")
                expect(item[5]).to.have.attr("href", "index.html#special-packages")
                expect(item[6]).to.contain.text("Booking Enquiry")
                expect(item[6]).to.have.attr("href", "booking.html?c1")
                expect(item[7]).to.contain.text("Reviews")
                expect(item[7]).to.have.attr("href", "index.html#reviews")
                expect(item[8]).to.contain.text("Contact")
                expect(item[8]).to.have.attr("href", "index.html#contact")
            })
            cy.wait(2000)
        })
    })
    // london
describe("Test London destination page", () => {
        it("navigates to London page", () => {
            cy.visit("https://brianwhelandublin.github.io/milestone-project-2/destination.html?c2")
        })
        it("tests London details", () => {
            cy.get(".des-page-title").should("contain", "London")
            cy.get(".des-background-img").should("have.attr", "style").should("contain", "london-bg.jpg")
            cy.get(".flag").should("be.visible")
            cy.get(".details-item").should("be.visible")
            cy.get("#map").should("be.visible")
            cy.get(".package").then(item => {
                expect(item[0]).to.contain.text("€199/ person sharing")
                expect(item[1]).to.contain.text("€249/ person sharing")
                expect(item[2]).to.contain.text("€399/ person sharing")
            })
        })
        it("Tests London navigation changes", () => {
            cy.get(".navigation-list").should("be.hidden")
            cy.get(".hamburger").click()
            cy.get(".navigation-list").should("be.visible")
            cy.get(".navigation-link").then(item => {
                expect(item[0]).to.contain.text("Home");
                expect(item[0]).to.have.attr("href", "index.html#home")
                expect(item[1]).to.contain.text("London Details")
                expect(item[1]).to.have.attr("href", "#details")
                expect(item[2]).to.contain.text("London Map")
                expect(item[2]).to.have.attr("href", "#map-section")
                expect(item[3]).to.contain.text("London Packages")
                expect(item[3]).to.have.attr("href", "#destination-packages")
                expect(item[4]).to.contain.text("All Destinations")
                expect(item[4]).to.have.attr("href", "index.html#destinations")
                expect(item[5]).to.contain.text("Package Specials")
                expect(item[5]).to.have.attr("href", "index.html#special-packages")
                expect(item[6]).to.contain.text("Booking Enquiry")
                expect(item[6]).to.have.attr("href", "booking.html?c2")
                expect(item[7]).to.contain.text("Reviews")
                expect(item[7]).to.have.attr("href", "index.html#reviews")
                expect(item[8]).to.contain.text("Contact")
                expect(item[8]).to.have.attr("href", "index.html#contact")
            })
            cy.wait(2000)
        })
    })
    // Madrid
describe("Test Madrid destination page", () => {
        it("navigates to Madrid page", () => {
            cy.visit("https://brianwhelandublin.github.io/milestone-project-2/destination.html?c3")
        })
        it("tests Madrid details", () => {
            cy.get(".des-page-title").should("contain", "Madrid")
            cy.get(".des-background-img").should("have.attr", "style").should("contain", "madrid-bg.jpg")
            cy.get(".flag").should("be.visible")
            cy.get(".details-item").should("be.visible")
            cy.get("#map").should("be.visible")
            cy.get(".package").then(item => {
                expect(item[0]).to.contain.text("€199/ person sharing")
                expect(item[1]).to.contain.text("€249/ person sharing")
                expect(item[2]).to.contain.text("€399/ person sharing")
            })
        })
        it("Tests Madrid navigation changes", () => {
            cy.get(".navigation-list").should("be.hidden")
            cy.get(".hamburger").click()
            cy.get(".navigation-list").should("be.visible")
            cy.get(".navigation-link").then(item => {
                expect(item[0]).to.contain.text("Home");
                expect(item[0]).to.have.attr("href", "index.html#home")
                expect(item[1]).to.contain.text("Madrid Details")
                expect(item[1]).to.have.attr("href", "#details")
                expect(item[2]).to.contain.text("Madrid Map")
                expect(item[2]).to.have.attr("href", "#map-section")
                expect(item[3]).to.contain.text("Madrid Packages")
                expect(item[3]).to.have.attr("href", "#destination-packages")
                expect(item[4]).to.contain.text("All Destinations")
                expect(item[4]).to.have.attr("href", "index.html#destinations")
                expect(item[5]).to.contain.text("Package Specials")
                expect(item[5]).to.have.attr("href", "index.html#special-packages")
                expect(item[6]).to.contain.text("Booking Enquiry")
                expect(item[6]).to.have.attr("href", "booking.html?c3")
                expect(item[7]).to.contain.text("Reviews")
                expect(item[7]).to.have.attr("href", "index.html#reviews")
                expect(item[8]).to.contain.text("Contact")
                expect(item[8]).to.have.attr("href", "index.html#contact")
            })
        })
    })
    // New York
describe("Test New York destination page", () => {
        it("navigates to New York page", () => {
            cy.visit("https://brianwhelandublin.github.io/milestone-project-2/destination.html?c4")
        })
        it("tests New York details", () => {
            cy.get(".des-page-title").should("contain", "New York")
            cy.get(".des-background-img").should("have.attr", "style").should("contain", "new-york-bg.jpg")
            cy.get(".flag").should("be.visible")
            cy.get(".details-item").should("be.visible")
            cy.get("#map").should("be.visible")
            cy.get(".package").then(item => {
                expect(item[0]).to.contain.text("€599/ person sharing")
                expect(item[1]).to.contain.text("€749/ person sharing")
                expect(item[2]).to.contain.text("€499/ person sharing")
            })
        })
        it("Tests New York navigation changes", () => {
            cy.get(".navigation-list").should("be.hidden")
            cy.get(".hamburger").click()
            cy.get(".navigation-list").should("be.visible")
            cy.get(".navigation-link").then(item => {
                expect(item[0]).to.contain.text("Home");
                expect(item[0]).to.have.attr("href", "index.html#home")
                expect(item[1]).to.contain.text("New York Details")
                expect(item[1]).to.have.attr("href", "#details")
                expect(item[2]).to.contain.text("New York Map")
                expect(item[2]).to.have.attr("href", "#map-section")
                expect(item[3]).to.contain.text("New York Packages")
                expect(item[3]).to.have.attr("href", "#destination-packages")
                expect(item[4]).to.contain.text("All Destinations")
                expect(item[4]).to.have.attr("href", "index.html#destinations")
                expect(item[5]).to.contain.text("Package Specials")
                expect(item[5]).to.have.attr("href", "index.html#special-packages")
                expect(item[6]).to.contain.text("Booking Enquiry")
                expect(item[6]).to.have.attr("href", "booking.html?c4")
                expect(item[7]).to.contain.text("Reviews")
                expect(item[7]).to.have.attr("href", "index.html#reviews")
                expect(item[8]).to.contain.text("Contact")
                expect(item[8]).to.have.attr("href", "index.html#contact")
            })
            cy.wait(2000)
        })
    })
    // paris
describe("Test Paris destination page", () => {
        it("navigates to Paris page", () => {
            cy.visit("https://brianwhelandublin.github.io/milestone-project-2/destination.html?c5")
        })
        it("tests Paris details", () => {
            cy.get(".des-page-title").should("contain", "Paris")
            cy.get(".des-background-img").should("have.attr", "style").should("contain", "paris-bg.jpg")
            cy.get(".flag").should("be.visible")
            cy.get(".details-item").should("be.visible")
            cy.get("#map").should("be.visible")
            cy.get(".package").then(item => {
                expect(item[0]).to.contain.text("€249/ person sharing")
                expect(item[1]).to.contain.text("399/ person sharing")
                expect(item[2]).to.contain.text("€299/ person sharing")
            })
        })
        it("Tests Paris navigation changes", () => {
            cy.get(".navigation-list").should("be.hidden")
            cy.get(".hamburger").click()
            cy.get(".navigation-list").should("be.visible")
            cy.get(".navigation-link").then(item => {
                expect(item[0]).to.contain.text("Home");
                expect(item[0]).to.have.attr("href", "index.html#home")
                expect(item[1]).to.contain.text("Paris Details")
                expect(item[1]).to.have.attr("href", "#details")
                expect(item[2]).to.contain.text("Paris Map")
                expect(item[2]).to.have.attr("href", "#map-section")
                expect(item[3]).to.contain.text("Paris Packages")
                expect(item[3]).to.have.attr("href", "#destination-packages")
                expect(item[4]).to.contain.text("All Destinations")
                expect(item[4]).to.have.attr("href", "index.html#destinations")
                expect(item[5]).to.contain.text("Package Specials")
                expect(item[5]).to.have.attr("href", "index.html#special-packages")
                expect(item[6]).to.contain.text("Booking Enquiry")
                expect(item[6]).to.have.attr("href", "booking.html?c5")
                expect(item[7]).to.contain.text("Reviews")
                expect(item[7]).to.have.attr("href", "index.html#reviews")
                expect(item[8]).to.contain.text("Contact")
                expect(item[8]).to.have.attr("href", "index.html#contact")
            })
            cy.wait(2000)
        })
    })
    // prague
describe("Test Prague destination page", () => {
    it("navigates to Prague page", () => {
        cy.visit("https://brianwhelandublin.github.io/milestone-project-2/destination.html?c6")
    })
    it("tests Prague details", () => {
        cy.get(".des-page-title").should("contain", "Prague")
        cy.get(".des-background-img").should("have.attr", "style").should("contain", "prague-bg.jpg")
        cy.get(".flag").should("be.visible")
        cy.get(".details-item").should("be.visible")
        cy.get("#map").should("be.visible")
        cy.get(".package").then(item => {
            expect(item[0]).to.contain.text("€249/ person sharing")
            expect(item[1]).to.contain.text("€299/ person sharing")
            expect(item[2]).to.contain.text("€349/ person sharing")
        })
    })
    it("Tests Prague navigation changes", () => {
        cy.get(".navigation-list").should("be.hidden")
        cy.get(".hamburger").click()
        cy.get(".navigation-list").should("be.visible")
        cy.get(".navigation-link").then(item => {
            expect(item[0]).to.contain.text("Home");
            expect(item[0]).to.have.attr("href", "index.html#home")
            expect(item[1]).to.contain.text("Prague Details")
            expect(item[1]).to.have.attr("href", "#details")
            expect(item[2]).to.contain.text("Prague Map")
            expect(item[2]).to.have.attr("href", "#map-section")
            expect(item[3]).to.contain.text("Prague Packages")
            expect(item[3]).to.have.attr("href", "#destination-packages")
            expect(item[4]).to.contain.text("All Destinations")
            expect(item[4]).to.have.attr("href", "index.html#destinations")
            expect(item[5]).to.contain.text("Package Specials")
            expect(item[5]).to.have.attr("href", "index.html#special-packages")
            expect(item[6]).to.contain.text("Booking Enquiry")
            expect(item[6]).to.have.attr("href", "booking.html?c6")
            expect(item[7]).to.contain.text("Reviews")
            expect(item[7]).to.have.attr("href", "index.html#reviews")
            expect(item[8]).to.contain.text("Contact")
            expect(item[8]).to.have.attr("href", "index.html#contact")
        })
        cy.wait(2000)
    })
})

// Rome
describe("Test Rome destination page", () => {
        it("navigates to Rome page", () => {
            cy.visit("https://brianwhelandublin.github.io/milestone-project-2/destination.html?c7")
        })
        it("tests Rome details", () => {
            cy.get(".des-page-title").should("contain", "Rome")
            cy.get(".des-background-img").should("have.attr", "style").should("contain", "rome-bg.jpg")
            cy.get(".flag").should("be.visible")
            cy.get(".details-item").should("be.visible")
            cy.get("#map").should("be.visible")
            cy.get(".package").then(item => {
                expect(item[0]).to.contain.text("€249/ person sharing")
                expect(item[1]).to.contain.text("€349/ person sharing")
                expect(item[2]).to.contain.text("€499/ person sharing")
            })
        })
        it("Tests Rome navigation changes", () => {
            cy.get(".navigation-list").should("be.hidden")
            cy.get(".hamburger").click()
            cy.get(".navigation-list").should("be.visible")
            cy.get(".navigation-link").then(item => {
                expect(item[0]).to.contain.text("Home");
                expect(item[0]).to.have.attr("href", "index.html#home")
                expect(item[1]).to.contain.text("Rome Details")
                expect(item[1]).to.have.attr("href", "#details")
                expect(item[2]).to.contain.text("Rome Map")
                expect(item[2]).to.have.attr("href", "#map-section")
                expect(item[3]).to.contain.text("Rome Packages")
                expect(item[3]).to.have.attr("href", "#destination-packages")
                expect(item[4]).to.contain.text("All Destinations")
                expect(item[4]).to.have.attr("href", "index.html#destinations")
                expect(item[5]).to.contain.text("Package Specials")
                expect(item[5]).to.have.attr("href", "index.html#special-packages")
                expect(item[6]).to.contain.text("Booking Enquiry")
                expect(item[6]).to.have.attr("href", "booking.html?c7")
                expect(item[7]).to.contain.text("Reviews")
                expect(item[7]).to.have.attr("href", "index.html#reviews")
                expect(item[8]).to.contain.text("Contact")
                expect(item[8]).to.have.attr("href", "index.html#contact")
            })
            cy.wait(2000)
        })
    })
    // singapore
describe("Test Singapore destination page", () => {
        it("navigates to Singapore page", () => {
            cy.visit("https://brianwhelandublin.github.io/milestone-project-2/destination.html?c8")
        })
        it("tests Singapore details", () => {
            cy.get(".des-page-title").should("contain", "Singapore")
            cy.get(".des-background-img").should("have.attr", "style").should("contain", "singapore-bg.jpg")
            cy.get(".flag").should("be.visible")
            cy.get(".details-item").should("be.visible")
            cy.get("#map").should("be.visible")
            cy.get(".package").then(item => {
                expect(item[0]).to.contain.text("€699/ person sharing")
                expect(item[1]).to.contain.text("€749/ person sharing")
                expect(item[2]).to.contain.text("€899/ person sharing")
            })
        })
        it("Tests Singapore navigation changes", () => {
            cy.get(".navigation-list").should("be.hidden")
            cy.get(".hamburger").click()
            cy.get(".navigation-list").should("be.visible")
            cy.get(".navigation-link").then(item => {
                expect(item[0]).to.contain.text("Home");
                expect(item[0]).to.have.attr("href", "index.html#home")
                expect(item[1]).to.contain.text("Singapore Details")
                expect(item[1]).to.have.attr("href", "#details")
                expect(item[2]).to.contain.text("Singapore Map")
                expect(item[2]).to.have.attr("href", "#map-section")
                expect(item[3]).to.contain.text("Singapore Packages")
                expect(item[3]).to.have.attr("href", "#destination-packages")
                expect(item[4]).to.contain.text("All Destinations")
                expect(item[4]).to.have.attr("href", "index.html#destinations")
                expect(item[5]).to.contain.text("Package Specials")
                expect(item[5]).to.have.attr("href", "index.html#special-packages")
                expect(item[6]).to.contain.text("Booking Enquiry")
                expect(item[6]).to.have.attr("href", "booking.html?c8")
                expect(item[7]).to.contain.text("Reviews")
                expect(item[7]).to.have.attr("href", "index.html#reviews")
                expect(item[8]).to.contain.text("Contact")
                expect(item[8]).to.have.attr("href", "index.html#contact")
            })
            cy.wait(2000)
        })
    })
    // Tokyo
describe("Test Tokyo destination page", () => {
        it("navigates to tokyo page", () => {
            cy.visit("https://brianwhelandublin.github.io/milestone-project-2/destination.html?c9")
        })
        it("tests Tokyo details", () => {
            cy.get(".des-page-title").should("contain", "Tokyo")
            cy.get(".des-background-img").should("have.attr", "style").should("contain", "tokyo-bg.jpg")
            cy.get(".flag").should("be.visible")
            cy.get(".details-item").should("be.visible")
            cy.get("#map").should("be.visible")
            cy.get(".package").then(item => {
                expect(item[0]).to.contain.text("€749/ person sharing")
                expect(item[1]).to.contain.text("€849/ person sharing")
                expect(item[2]).to.contain.text("€999/ person sharing")
            })
        })
        it("Tests Tokyo navigation changes", () => {
            cy.get(".navigation-list").should("be.hidden")
            cy.get(".hamburger").click()
            cy.get(".navigation-list").should("be.visible")
            cy.get(".navigation-link").then(item => {
                expect(item[0]).to.contain.text("Home");
                expect(item[0]).to.have.attr("href", "index.html#home")
                expect(item[1]).to.contain.text("Tokyo Details")
                expect(item[1]).to.have.attr("href", "#details")
                expect(item[2]).to.contain.text("Tokyo Map")
                expect(item[2]).to.have.attr("href", "#map-section")
                expect(item[3]).to.contain.text("Tokyo Packages")
                expect(item[3]).to.have.attr("href", "#destination-packages")
                expect(item[4]).to.contain.text("All Destinations")
                expect(item[4]).to.have.attr("href", "index.html#destinations")
                expect(item[5]).to.contain.text("Package Specials")
                expect(item[5]).to.have.attr("href", "index.html#special-packages")
                expect(item[6]).to.contain.text("Booking Enquiry")
                expect(item[6]).to.have.attr("href", "booking.html?c9")
                expect(item[7]).to.contain.text("Reviews")
                expect(item[7]).to.have.attr("href", "index.html#reviews")
                expect(item[8]).to.contain.text("Contact")
                expect(item[8]).to.have.attr("href", "index.html#contact")
            })
            cy.wait(2000)
        })
    })
    // antigua
describe("Test Antigua destination page", () => {
        it("navigates to Antigua page", () => {
            cy.visit("https://brianwhelandublin.github.io/milestone-project-2/destination.html?b0")
        })
        it("tests Antigua details", () => {
            cy.get(".des-page-title").should("contain", "Antigua")
            cy.get(".des-background-img").should("have.attr", "style").should("contain", "antigua-bg.jpg")
            cy.get(".flag").should("be.visible")
            cy.get(".details-item").should("be.visible")
            cy.get("#map").should("be.visible")
            cy.get(".package").then(item => {
                expect(item[0]).to.contain.text("€1099/ person sharing")
                expect(item[1]).to.contain.text("€1249/ person sharing")
                expect(item[2]).to.contain.text("€1399/ person sharing")
            })
        })
        it("Tests Antigua navigation changes", () => {
            cy.get(".navigation-list").should("be.hidden")
            cy.get(".hamburger").click()
            cy.get(".navigation-list").should("be.visible")
            cy.get(".navigation-link").then(item => {
                expect(item[0]).to.contain.text("Home");
                expect(item[0]).to.have.attr("href", "index.html#home")
                expect(item[1]).to.contain.text("Antigua Details")
                expect(item[1]).to.have.attr("href", "#details")
                expect(item[2]).to.contain.text("Antigua Map")
                expect(item[2]).to.have.attr("href", "#map-section")
                expect(item[3]).to.contain.text("Antigua Packages")
                expect(item[3]).to.have.attr("href", "#destination-packages")
                expect(item[4]).to.contain.text("All Destinations")
                expect(item[4]).to.have.attr("href", "index.html#destinations")
                expect(item[5]).to.contain.text("Package Specials")
                expect(item[5]).to.have.attr("href", "index.html#special-packages")
                expect(item[6]).to.contain.text("Booking Enquiry")
                expect(item[6]).to.have.attr("href", "booking.html?b0")
                expect(item[7]).to.contain.text("Reviews")
                expect(item[7]).to.have.attr("href", "index.html#reviews")
                expect(item[8]).to.contain.text("Contact")
                expect(item[8]).to.have.attr("href", "index.html#contact")
            })
            cy.wait(2000)
        })
    })
    // Bali
describe("Test Bali destination page", () => {
        it("navigates to Bali page", () => {
            cy.visit("https://brianwhelandublin.github.io/milestone-project-2/destination.html?b1")
        })
        it("tests Bali details", () => {
            cy.get(".des-page-title").should("contain", "Bali")
            cy.get(".des-background-img").should("have.attr", "style").should("contain", "bali-bg.jpg")
            cy.get(".flag").should("be.visible")
            cy.get(".details-item").should("be.visible")
            cy.get("#map").should("be.visible")
            cy.get(".package").then(item => {
                expect(item[0]).to.contain.text("€999/ person sharing")
                expect(item[1]).to.contain.text("€1149/ person sharing")
                expect(item[2]).to.contain.text("€1299/ person sharing")
            })
        })
        it("Tests Bali navigation changes", () => {
            cy.get(".navigation-list").should("be.hidden")
            cy.get(".hamburger").click()
            cy.get(".navigation-list").should("be.visible")
            cy.get(".navigation-link").then(item => {
                expect(item[0]).to.contain.text("Home");
                expect(item[0]).to.have.attr("href", "index.html#home")
                expect(item[1]).to.contain.text("Bali Details")
                expect(item[1]).to.have.attr("href", "#details")
                expect(item[2]).to.contain.text("Bali Map")
                expect(item[2]).to.have.attr("href", "#map-section")
                expect(item[3]).to.contain.text("Bali Packages")
                expect(item[3]).to.have.attr("href", "#destination-packages")
                expect(item[4]).to.contain.text("All Destinations")
                expect(item[4]).to.have.attr("href", "index.html#destinations")
                expect(item[5]).to.contain.text("Package Specials")
                expect(item[5]).to.have.attr("href", "index.html#special-packages")
                expect(item[6]).to.contain.text("Booking Enquiry")
                expect(item[6]).to.have.attr("href", "booking.html?b1")
                expect(item[7]).to.contain.text("Reviews")
                expect(item[7]).to.have.attr("href", "index.html#reviews")
                expect(item[8]).to.contain.text("Contact")
                expect(item[8]).to.have.attr("href", "index.html#contact")
            })
            cy.wait(2000)
        })
    })
    // Capri
describe("Test Capri destination page", () => {
        it("navigates to Capri page", () => {
            cy.visit("https://brianwhelandublin.github.io/milestone-project-2/destination.html?b2")
        })
        it("tests Capri details", () => {
            cy.get(".des-page-title").should("contain", "Capri")
            cy.get(".des-background-img").should("have.attr", "style").should("contain", "capri-bg.jpg")
            cy.get(".flag").should("be.visible")
            cy.get(".details-item").should("be.visible")
            cy.get("#map").should("be.visible")
            cy.get(".package").then(item => {
                expect(item[0]).to.contain.text("€699/ person sharing")
                expect(item[1]).to.contain.text("€749/ person sharing")
                expect(item[2]).to.contain.text("€899/ person sharing")
            })
        })
        it("Tests Capri navigation changes", () => {
            cy.get(".navigation-list").should("be.hidden")
            cy.get(".hamburger").click()
            cy.get(".navigation-list").should("be.visible")
            cy.get(".navigation-link").then(item => {
                expect(item[0]).to.contain.text("Home");
                expect(item[0]).to.have.attr("href", "index.html#home")
                expect(item[1]).to.contain.text("Capri Details")
                expect(item[1]).to.have.attr("href", "#details")
                expect(item[2]).to.contain.text("Capri Map")
                expect(item[2]).to.have.attr("href", "#map-section")
                expect(item[3]).to.contain.text("Capri Packages")
                expect(item[3]).to.have.attr("href", "#destination-packages")
                expect(item[4]).to.contain.text("All Destinations")
                expect(item[4]).to.have.attr("href", "index.html#destinations")
                expect(item[5]).to.contain.text("Package Specials")
                expect(item[5]).to.have.attr("href", "index.html#special-packages")
                expect(item[6]).to.contain.text("Booking Enquiry")
                expect(item[6]).to.have.attr("href", "booking.html?b2")
                expect(item[7]).to.contain.text("Reviews")
                expect(item[7]).to.have.attr("href", "index.html#reviews")
                expect(item[8]).to.contain.text("Contact")
                expect(item[8]).to.have.attr("href", "index.html#contact")
            })
            cy.wait(2000)
        })
    })
    // fiji
describe("Test Fiji destination page", () => {
        it("navigates to Fiji page", () => {
            cy.visit("https://brianwhelandublin.github.io/milestone-project-2/destination.html?b3")
        })
        it("tests Fiji details", () => {
            cy.get(".des-page-title").should("contain", "Fiji")
            cy.get(".des-background-img").should("have.attr", "style").should("contain", "fiji-bg.jpg")
            cy.get(".flag").should("be.visible")
            cy.get(".details-item").should("be.visible")
            cy.get("#map").should("be.visible")
            cy.get(".package").then(item => {
                expect(item[0]).to.contain.text("€1299/ person sharing")
                expect(item[1]).to.contain.text("€1449/ person sharing")
                expect(item[2]).to.contain.text("€1599/ person sharing")
            })
        })
        it("Tests Fiji navigation changes", () => {
            cy.get(".navigation-list").should("be.hidden")
            cy.get(".hamburger").click()
            cy.get(".navigation-list").should("be.visible")
            cy.get(".navigation-link").then(item => {
                expect(item[0]).to.contain.text("Home");
                expect(item[0]).to.have.attr("href", "index.html#home")
                expect(item[1]).to.contain.text("Fiji Details")
                expect(item[1]).to.have.attr("href", "#details")
                expect(item[2]).to.contain.text("Fiji Map")
                expect(item[2]).to.have.attr("href", "#map-section")
                expect(item[3]).to.contain.text("Fiji Packages")
                expect(item[3]).to.have.attr("href", "#destination-packages")
                expect(item[4]).to.contain.text("All Destinations")
                expect(item[4]).to.have.attr("href", "index.html#destinations")
                expect(item[5]).to.contain.text("Package Specials")
                expect(item[5]).to.have.attr("href", "index.html#special-packages")
                expect(item[6]).to.contain.text("Booking Enquiry")
                expect(item[6]).to.have.attr("href", "booking.html?b3")
                expect(item[7]).to.contain.text("Reviews")
                expect(item[7]).to.have.attr("href", "index.html#reviews")
                expect(item[8]).to.contain.text("Contact")
                expect(item[8]).to.have.attr("href", "index.html#contact")
            })
            cy.wait(2000)
        })
    })
    // Koh Phi phi
describe("Test Koh Phi Phi destination page", () => {
        it("navigates to Koh phi phi page", () => {
            cy.visit("https://brianwhelandublin.github.io/milestone-project-2/destination.html?b4")
        })
        it("tests Koh Phi Phi details", () => {
            cy.get(".des-page-title").should("contain", "Koh Phi Phi")
            cy.get(".des-background-img").should("have.attr", "style").should("contain", "koh-phi-phi-bg.jpg")
            cy.get(".flag").should("be.visible")
            cy.get(".details-item").should("be.visible")
            cy.get("#map").should("be.visible")
            cy.get(".package").then(item => {
                expect(item[0]).to.contain.text("€899/ person sharing")
                expect(item[1]).to.contain.text("€949/ person sharing")
                expect(item[2]).to.contain.text("€1099/ person sharing")
            })
        })
        it("Tests Koh Phi Phi navigation changes", () => {
            cy.get(".navigation-list").should("be.hidden")
            cy.get(".hamburger").click()
            cy.get(".navigation-list").should("be.visible")
            cy.get(".navigation-link").then(item => {
                expect(item[0]).to.contain.text("Home");
                expect(item[0]).to.have.attr("href", "index.html#home")
                expect(item[1]).to.contain.text("Koh Phi Phi Details")
                expect(item[1]).to.have.attr("href", "#details")
                expect(item[2]).to.contain.text("Koh Phi Phi Map")
                expect(item[2]).to.have.attr("href", "#map-section")
                expect(item[3]).to.contain.text("Koh Phi Phi Packages")
                expect(item[3]).to.have.attr("href", "#destination-packages")
                expect(item[4]).to.contain.text("All Destinations")
                expect(item[4]).to.have.attr("href", "index.html#destinations")
                expect(item[5]).to.contain.text("Package Specials")
                expect(item[5]).to.have.attr("href", "index.html#special-packages")
                expect(item[6]).to.contain.text("Booking Enquiry")
                expect(item[6]).to.have.attr("href", "booking.html?b4")
                expect(item[7]).to.contain.text("Reviews")
                expect(item[7]).to.have.attr("href", "index.html#reviews")
                expect(item[8]).to.contain.text("Contact")
                expect(item[8]).to.have.attr("href", "index.html#contact")
            })
            cy.wait(2000)
        })
    })
    // Maldives
describe("Test Maldives destination page", () => {
        it("navigates Maldives page", () => {
            cy.visit("https://brianwhelandublin.github.io/milestone-project-2/destination.html?b5")
        })
        it("tests Maldives details", () => {
            cy.get(".des-page-title").should("contain", "Maldives")
            cy.get(".des-background-img").should("have.attr", "style").should("contain", "maldives-bg.jpg")
            cy.get(".flag").should("be.visible")
            cy.get(".details-item").should("be.visible")
            cy.get("#map").should("be.visible")
            cy.get(".package").then(item => {
                expect(item[0]).to.contain.text("€1499/ person sharing")
                expect(item[1]).to.contain.text("€1649/ person sharing")
                expect(item[2]).to.contain.text("€1999/ person sharing")
            })
        })
        it("Tests Maldives navigation changes", () => {
            cy.get(".navigation-list").should("be.hidden")
            cy.get(".hamburger").click()
            cy.get(".navigation-list").should("be.visible")
            cy.get(".navigation-link").then(item => {
                expect(item[0]).to.contain.text("Home");
                expect(item[0]).to.have.attr("href", "index.html#home")
                expect(item[1]).to.contain.text("Maldives Details")
                expect(item[1]).to.have.attr("href", "#details")
                expect(item[2]).to.contain.text("Maldives Map")
                expect(item[2]).to.have.attr("href", "#map-section")
                expect(item[3]).to.contain.text("Maldives Packages")
                expect(item[3]).to.have.attr("href", "#destination-packages")
                expect(item[4]).to.contain.text("All Destinations")
                expect(item[4]).to.have.attr("href", "index.html#destinations")
                expect(item[5]).to.contain.text("Package Specials")
                expect(item[5]).to.have.attr("href", "index.html#special-packages")
                expect(item[6]).to.contain.text("Booking Enquiry")
                expect(item[6]).to.have.attr("href", "booking.html?b5")
                expect(item[7]).to.contain.text("Reviews")
                expect(item[7]).to.have.attr("href", "index.html#reviews")
                expect(item[8]).to.contain.text("Contact")
                expect(item[8]).to.have.attr("href", "index.html#contact")
            })
            cy.wait(2000)
        })
    })
    // Seychelles
describe("Test Seychelles destination page", () => {
        it("navigates Seychelles page", () => {
            cy.visit("https://brianwhelandublin.github.io/milestone-project-2/destination.html?b6")
        })
        it("tests Seychelles details", () => {
            cy.get(".des-page-title").should("contain", "Seychelles")
            cy.get(".des-background-img").should("have.attr", "style").should("contain", "seychelles-bg.jpg")
            cy.get(".flag").should("be.visible")
            cy.get(".details-item").should("be.visible")
            cy.get("#map").should("be.visible")
            cy.get(".package").then(item => {
                expect(item[0]).to.contain.text("€1299/ person sharing")
                expect(item[1]).to.contain.text("€1349/ person sharing")
                expect(item[2]).to.contain.text("€1499/ person sharing")
            })
        })
        it("Tests Seychelles navigation changes", () => {
            cy.get(".navigation-list").should("be.hidden")
            cy.get(".hamburger").click()
            cy.get(".navigation-list").should("be.visible")
            cy.get(".navigation-link").then(item => {
                expect(item[0]).to.contain.text("Home");
                expect(item[0]).to.have.attr("href", "index.html#home")
                expect(item[1]).to.contain.text("Seychelles Details")
                expect(item[1]).to.have.attr("href", "#details")
                expect(item[2]).to.contain.text("Seychelles Map")
                expect(item[2]).to.have.attr("href", "#map-section")
                expect(item[3]).to.contain.text("Seychelles Packages")
                expect(item[3]).to.have.attr("href", "#destination-packages")
                expect(item[4]).to.contain.text("All Destinations")
                expect(item[4]).to.have.attr("href", "index.html#destinations")
                expect(item[5]).to.contain.text("Package Specials")
                expect(item[5]).to.have.attr("href", "index.html#special-packages")
                expect(item[6]).to.contain.text("Booking Enquiry")
                expect(item[6]).to.have.attr("href", "booking.html?b6")
                expect(item[7]).to.contain.text("Reviews")
                expect(item[7]).to.have.attr("href", "index.html#reviews")
                expect(item[8]).to.contain.text("Contact")
                expect(item[8]).to.have.attr("href", "index.html#contact")
            })
            cy.wait(2000)
        })
    })
    // philippines
describe("Test Philippines destination page", () => {
        it("navigates Philippines page", () => {
            cy.visit("https://brianwhelandublin.github.io/milestone-project-2/destination.html?b7")
        })
        it("tests Philippines details", () => {
            cy.get(".des-page-title").should("contain", "Philippines")
            cy.get(".des-background-img").should("have.attr", "style").should("contain", "philippines-bg.jpg")
            cy.get(".flag").should("be.visible")
            cy.get(".details-item").should("be.visible")
            cy.get("#map").should("be.visible")
            cy.get(".package").then(item => {
                expect(item[0]).to.contain.text("€999/ person sharing")
                expect(item[1]).to.contain.text("€1149/ person sharing")
                expect(item[2]).to.contain.text("€1299/ person sharing")
            })
        })
        it("Tests Philippines navigation changes", () => {
            cy.get(".navigation-list").should("be.hidden")
            cy.get(".hamburger").click()
            cy.get(".navigation-list").should("be.visible")
            cy.get(".navigation-link").then(item => {
                expect(item[0]).to.contain.text("Home");
                expect(item[0]).to.have.attr("href", "index.html#home")
                expect(item[1]).to.contain.text("Philippines Details")
                expect(item[1]).to.have.attr("href", "#details")
                expect(item[2]).to.contain.text("Philippines Map")
                expect(item[2]).to.have.attr("href", "#map-section")
                expect(item[3]).to.contain.text("Philippines Packages")
                expect(item[3]).to.have.attr("href", "#destination-packages")
                expect(item[4]).to.contain.text("All Destinations")
                expect(item[4]).to.have.attr("href", "index.html#destinations")
                expect(item[5]).to.contain.text("Package Specials")
                expect(item[5]).to.have.attr("href", "index.html#special-packages")
                expect(item[6]).to.contain.text("Booking Enquiry")
                expect(item[6]).to.have.attr("href", "booking.html?b7")
                expect(item[7]).to.contain.text("Reviews")
                expect(item[7]).to.have.attr("href", "index.html#reviews")
                expect(item[8]).to.contain.text("Contact")
                expect(item[8]).to.have.attr("href", "index.html#contact")
            })
            cy.wait(2000)
        })
    })
    // tulum
describe("Test Tulum destination page", () => {
    it("navigates Tulum page", () => {
        cy.visit("https://brianwhelandublin.github.io/milestone-project-2/destination.html?b8")
    })
    it("tests New York details", () => {
        cy.get(".des-page-title").should("contain", "Tulum")
        cy.get(".des-background-img").should("have.attr", "style").should("contain", "tulum-bg.jpg")
        cy.get(".flag").should("be.visible")
        cy.get(".details-item").should("be.visible")
        cy.get("#map").should("be.visible")
        cy.get(".package").then(item => {
            expect(item[0]).to.contain.text("€1399/ person sharing")
            expect(item[1]).to.contain.text("€1549/ person sharing")
            expect(item[2]).to.contain.text("€1799/ person sharing")
        })
    })
    it("Tests Tulum navigation changes", () => {
        cy.get(".navigation-list").should("be.hidden")
        cy.get(".hamburger").click()
        cy.get(".navigation-list").should("be.visible")
        cy.get(".navigation-link").then(item => {
            expect(item[0]).to.contain.text("Home");
            expect(item[0]).to.have.attr("href", "index.html#home")
            expect(item[1]).to.contain.text("Tulum Details")
            expect(item[1]).to.have.attr("href", "#details")
            expect(item[2]).to.contain.text("Tulum Map")
            expect(item[2]).to.have.attr("href", "#map-section")
            expect(item[3]).to.contain.text("Tulum Packages")
            expect(item[3]).to.have.attr("href", "#destination-packages")
            expect(item[4]).to.contain.text("All Destinations")
            expect(item[4]).to.have.attr("href", "index.html#destinations")
            expect(item[5]).to.contain.text("Package Specials")
            expect(item[5]).to.have.attr("href", "index.html#special-packages")
            expect(item[6]).to.contain.text("Booking Enquiry")
            expect(item[6]).to.have.attr("href", "booking.html?b8")
            expect(item[7]).to.contain.text("Reviews")
            expect(item[7]).to.have.attr("href", "index.html#reviews")
            expect(item[8]).to.contain.text("Contact")
            expect(item[8]).to.have.attr("href", "index.html#contact")
        })
        cy.wait(2000)
    })
})
describe("Test Santorini destination page", () => {
    it("navigates to dubai page", () => {
        cy.visit("https://brianwhelandublin.github.io/milestone-project-2/destination.html?b9")
    })
    it("tests Santorini details", () => {
        cy.get(".des-page-title").should("contain", "Santorini")
        cy.get(".des-background-img").should("have.attr", "style").should("contain", "santorini-bg.jpg")
        cy.get(".flag").should("be.visible")
        cy.get(".details-item").should("be.visible")
        cy.get("#map").should("be.visible")
        cy.get(".package").then(item => {
            expect(item[0]).to.contain.text("€1099/ person sharing")
            expect(item[1]).to.contain.text("€1249/ person sharing")
            expect(item[2]).to.contain.text("€1199/ person sharing")
        })
    })
    it("Tests Santorini navigation changes", () => {
        cy.get(".navigation-list").should("be.hidden")
        cy.get(".hamburger").click()
        cy.get(".navigation-list").should("be.visible")
        cy.get(".navigation-link").then(item => {
            expect(item[0]).to.contain.text("Home");
            expect(item[0]).to.have.attr("href", "index.html#home")
            expect(item[1]).to.contain.text("Santorini Details")
            expect(item[1]).to.have.attr("href", "#details")
            expect(item[2]).to.contain.text("Santorini Map")
            expect(item[2]).to.have.attr("href", "#map-section")
            expect(item[3]).to.contain.text("Santorini Packages")
            expect(item[3]).to.have.attr("href", "#destination-packages")
            expect(item[4]).to.contain.text("All Destinations")
            expect(item[4]).to.have.attr("href", "index.html#destinations")
            expect(item[5]).to.contain.text("Package Specials")
            expect(item[5]).to.have.attr("href", "index.html#special-packages")
            expect(item[6]).to.contain.text("Booking Enquiry")
            expect(item[6]).to.have.attr("href", "booking.html?b9")
            expect(item[7]).to.contain.text("Reviews")
            expect(item[7]).to.have.attr("href", "index.html#reviews")
            expect(item[8]).to.contain.text("Contact")
            expect(item[8]).to.have.attr("href", "index.html#contact")
        })
        cy.wait(2000)
    })
})
describe("Empty destination page", () => {
    it("navigates destination page with no code", () => {
        cy.visit("https://brianwhelandublin.github.io/milestone-project-2/destination.html")
    })
    it("tests error details", () => {
        cy.get(".no-destination").should("contain", "Opps no destination details")
    })

    it("Tests navigation changes", () => {
        cy.get(".navigation-list").should("be.hidden")
        cy.get(".hamburger").click()
        cy.get(".navigation-list").should("be.visible")
        cy.get(".navigation-link").then(item => {
            expect(item[0]).to.contain.text("Home");
            expect(item[0]).to.have.attr("href", "index.html#home")
            expect(item[1]).to.contain.text("Destination Details")
            expect(item[1]).to.have.attr("href", "#details")
            expect(item[2]).to.contain.text("Map")
            expect(item[2]).to.have.attr("href", "#map-section")
            expect(item[3]).to.contain.text("Packages")
            expect(item[3]).to.have.attr("href", "#destination-packages")
            expect(item[4]).to.contain.text("All Destinations")
            expect(item[4]).to.have.attr("href", "index.html#destinations")
            expect(item[5]).to.contain.text("Package Specials")
            expect(item[5]).to.have.attr("href", "index.html#special-packages")
            expect(item[6]).to.contain.text("Booking Enquiry")
            expect(item[6]).to.have.attr("href", "booking.html")
            expect(item[7]).to.contain.text("Reviews")
            expect(item[7]).to.have.attr("href", "index.html#reviews")
            expect(item[8]).to.contain.text("Contact")
            expect(item[8]).to.have.attr("href", "index.html#contact")
        })
        cy.wait(2000)
    })
})
describe("Empty destination page wrong code", () => {
    it("navigates destination page with wrong code", () => {
        cy.visit("https://brianwhelandublin.github.io/milestone-project-2/destination.html?c8897")
    })
    it("tests error details", () => {
        cy.get(".no-destination").should("contain", "Opps no destination details")
    })

    it("Tests navigation changes", () => {
        cy.get(".navigation-list").should("be.hidden")
        cy.get(".hamburger").click()
        cy.get(".navigation-list").should("be.visible")
        cy.get(".navigation-link").then(item => {
            expect(item[0]).to.contain.text("Home");
            expect(item[0]).to.have.attr("href", "index.html#home")
            expect(item[1]).to.contain.text("Destination Details")
            expect(item[1]).to.have.attr("href", "#details")
            expect(item[2]).to.contain.text("Map")
            expect(item[2]).to.have.attr("href", "#map-section")
            expect(item[3]).to.contain.text("Packages")
            expect(item[3]).to.have.attr("href", "#destination-packages")
            expect(item[4]).to.contain.text("All Destinations")
            expect(item[4]).to.have.attr("href", "index.html#destinations")
            expect(item[5]).to.contain.text("Package Specials")
            expect(item[5]).to.have.attr("href", "index.html#special-packages")
            expect(item[6]).to.contain.text("Booking Enquiry")
            expect(item[6]).to.have.attr("href", "booking.html")
            expect(item[7]).to.contain.text("Reviews")
            expect(item[7]).to.have.attr("href", "index.html#reviews")
            expect(item[8]).to.contain.text("Contact")
            expect(item[8]).to.have.attr("href", "index.html#contact")
        })
    })
})